### ISSUE TITLE
[BUG] More granular training configuration (selective labels)

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#599] opened 2021-02-23 14:47 UTC
Categories with spaces, e.g. Species A, should have quotes when input to labels.txt during model training: "Species A"

**Comment by subdavis** [comment] 2021-10-01 19:11
Might need to just let people upload labels.txt or since people might want to combine labels.

**Comment by subdavis** [comment] 2021-10-05 15:44
Possible duplicate of #970 -- one or the other should close.

**Closed** 2021-12-20 19:46 UTC
Labels: Type: Feature Request, Affects: Usability, Stakeholder: NOAA
