### ISSUE TITLE
[FEATURE] Reload/request reload after data import

### ISSUE THREAD

**Issue by russelldj** [Kitware/dive#867] opened 2021-07-30 12:45 UTC
**Is your feature request related to a problem? If so, Please describe.**
I just tried the import feature in the annotator window and it's great. However, I assumed it was broken because nothing in the viewer changed until I refreshed the page. 

**Describe the solution you'd like**
I think an auto-refresh would be nice.

**Describe alternatives you've considered**
Ask if the user wants to reload, in case some state would be deleted.

**Comment by BryonLewis** [comment] 2021-07-30 13:28
The intention is that it should do an automatic reload when you upload, there was a bug I found last night that may be preventing this with larger annotation files.

Could you provide two pieces of information on this?

- What was the approximate size of the annotation files you were uploading in MB?
- Additionally could you try this again and open the chrome-dev tools (CTRL+SHIFT+I) and see if there is an error in the console?

**Comment by russelldj** [comment] 2021-07-30 15:36
My accounts shut down in 25 minutes so I probably won't be getting to it today...maybe as an external collaborator. The files were added on [this merge request](https://gitlab.kitware.com/viame/viame_dvc/-/merge_requests/9)  to the DVC repo.

**Comment by russelldj** [comment] 2021-07-30 15:37
The 2007 collect didn't load at all for me, maybe it was too big.

**Comment by BryonLewis** [comment] 2021-09-15 13:04
I believe steps to reproduce:

- Clone https://viame.kitware.com/#/viewer/605befa98ba6bae828a05f5b into your own public folder.
- In the slack chat search for: "sealions_2007_v9_deepmac.kwcoco.json" and download the kwcoco file.
- Load up your cloned version and then import the kwcoco file.  It may take a few moments because it is a ~37MB file.  So the importing icon may be spinning for a while.
- After complete the system should autokick itself into reloading the data and then you should be able to see the poloygons on the sealions.

I think the auto-reload after the upload should satisfy this issue to close it out.

**Comment by BryonLewis** [comment] 2021-09-16 13:38
Confirmed that this is fixed.

**Closed by BryonLewis** 2021-09-16 13:38 UTC
Labels: Type: Feature Request
