### ISSUE TITLE
[FEATURE] Add side page that lists all object categories in all public folders

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#648] opened 2021-03-18 15:37 UTC
As a follow-up, the ability to click the object label and see any videos with annotations on them in a list would be helpful like

video name - video user  with links

**Comment by aashish24** [comment] 2021-03-18 18:28
so present the username with hyperlink on each video label? Or there is more to it?

**Comment by subdavis** [comment] 2021-03-18 22:06
Please add more details.

* What is an "object label"?
* What is a "video user"?
* What page is this on?  The viewer?  The data manager table?

**Comment by subdavis** [comment] 2021-03-18 22:16
**Is your feature request related to a problem? If so, Please describe.**

<please include what is motivating this feature request>

**Describe the solution you'd like**

Create a page (for all users? admins? dynamic based on user role?) that lists all types of objects across all datasets.

* This list should be collapsible or somehow show links to all the videos that include this object.

**Additional context**

Anything else?  Does some other piece of software you know of have this?  Can we steal ideas from somewhere else?

-------------------

I think this is a good idea.  It seems like it would be building towards having searchable data repository for doing vision stuff.

It would require a lot more gymnastics on the server side than we have right now.  I'm not really sure what this would look like, we might have to reconsider #306.

**Comment by subdavis** [comment] 2021-03-22 17:20
This appears to be a duplicate of #648, let's merge discussion into that issue?

**Comment by subdavis** [comment] 2021-03-25 17:10
I'm going to make a very rough pass on generating some summary data using celery.

**Closed** 2021-03-27 13:17 UTC
Labels: enhancement
