### ISSUE TITLE
[BUG] Desktop - flickering in image display when making lots of annotation fast

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#495] opened 2020-12-14 14:05 UTC
When I go into continuous mode and make lots of annotations fast the screen flickers to black (didn't capture on tape) but when I do something like the below

![flicker](https://user-images.githubusercontent.com/2353972/102090438-78e7d400-3deb-11eb-9d7d-4af8945f0d28.png)

**Comment by subdavis** [comment] 2020-12-14 15:34
Tried in both web and desktop (windows).

1. From empty image sequence
2. Configure track creation settings: Detection, Continuous.
3. Rapidly drag small boxes quickly.

Cannot reproduce.

**Comment by waxlamp** [comment] 2022-01-12 16:07
> Cannot reproduce.

Closing. Re-open if there's a repro.

**Closed by waxlamp** 2022-01-12 16:07 UTC
Labels: Type: bug
