### ISSUE TITLE
[FEATURE] Improve load times for sequences with lots of detections

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#698] opened 2021-04-13 14:52 UTC
Maybe there's a way to not load all of the detections at once?

**Comment by subdavis** [comment] 2021-04-13 14:54
Bryon and I have talked about this extensively.  It needs to be done.

I'd like to start with just cutting down on the unnecessary bulk of schema that we already have and see how that works.  If it doesn't we can start to think about incremental loading.

**Comment by subdavis** [comment] 2021-06-26 17:15
I'd like to prioritize this and #306.

- [ ] Migrate annotation data into mongo for fast incremental read/write at the track level.  The new mongo collection will be tracks.
- [ ] Migrate our GeoJSON feature data into something like the KWCOCO schema.
- [ ] Change our top-level schema to include version number, schema type, and the ability to add new fields later.

## Schema

We should redo a bit of the schema for the DIVE json format. We should _not_ unify with any existing formats because they are not optimized in a track-centric way that this application requres.

KWCOCO is close, and has many similarities with DIVE json, but would not be ideal for the way we want to store and index data.  That said, there are things we can learn from the KWCOCO format.

As long as we're making breaking changes to the schema, we should take this opportunity to extend the schema to support non-breaking future changes.

``` json
{
  "version": "2",
  "schema": "dive",
  "tracks": { /* the existing track dict goes in here */ }
}
```

If we need to add new sections like `"images"` in the future it will be safe to do so without complex migrations.


 ##  Database

* If we have track documents, they can't be larger than 16MB.  I don't see how this could really ever be an issue.
* We still need to track revision history.  We can use soft delete and a revision ID marker, but there may be pitfalls to doing this.  We should consult with the mongo experts.  New tracks create a new document with a higher ID.  Deletes create a new revision with a deletion flag.

## Migration - Web

Migration should be done during an offline maintenance window where the latest version of ever dataset's annotations get populated in the DB.  Migrations will not capture revision history because we cannot guarantee every dataset has a complete ordered revision history.  Migration will happen in an external script and should be idempotent.

## Migrations - Desktop

Migrations should be run at dataset load time in Node.js.  The desktop will continue to store data as JSON files on disk with revision history moved into the aux folder.  

Other stakeholders have asked for a more "in-place" option for looking at data with DIVE, so we should evaluate how these proposed changes impact them.

## Blast Radius

Wide-reaching impact to project.  We could do this in phases where we don't do the GeoJSON -> kwcoco switch until later.

Estimated time: 2-3 weeks.

## Impact

* Enables incremental load for faster load times
* Enables incremental save for much faster save times (#275)
* Data in database will give us many more options for being able to report the annotation contents of the server, including a version of the stats page with a complete list of all annotated types, deep usage stats, etc.
* Resilience against future schema changes
* Easier interoperability with KwCOCO.
* Better options for describing image sort order for data sets where image sequence ordering is unconventional.
* Better options for interoperability of web and desktop, since new schema would allow us to export full dataset metadata and attributes into one file if we want.

**Comment by subdavis** [comment] 2021-06-28 18:13
Hold off on switch away from GeoJSON.  This will significantly reduce complexity of migrations.

**Comment by subdavis** [comment] 2021-11-11 19:47
Closing as duplicate of #306 since that is the only possible approach to not loading everything at once.

**Closed by subdavis** 2021-11-11 19:47 UTC
Labels: Affects: Usability, Type: Housekeeping
