### ISSUE TITLE
[FEATURE] Instead of "Inactive" for jobs in queue say "In Queue" or similar to not confuse users

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#848] opened 2021-07-16 03:09 UTC
Inactive might imply it's not running for another reason than just being in a queue

**Comment by subdavis** [comment] 2021-07-16 12:29
This was fixed a while ago, where do you see "inactive"? We can't change it in the girder client, but it's already fixed in the dive client.

**Comment by subdavis** [comment] 2021-07-17 11:19
duplicate of #561 

![Screenshot from 2021-07-17 07-17-33](https://user-images.githubusercontent.com/4214172/126035190-870dbfb9-268d-46fe-9e95-f273d35db13d.png)

**Closed by subdavis** 2021-07-17 11:19 UTC
Labels: Status: duplicate

**Comment by mattdawkins** [comment] 2021-07-19 14:01
Yeah I was looking in girder not front end doesn't matter then
