### ISSUE TITLE
Decide on interfaces and workflows for fast user-initialized segmentation

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#271] opened 2020-08-11 15:31 UTC
For example, user clicks a location on a fish, system comes up with initial segmentation mask, user clicks another region control point indicating it either belongs or doesn't belong to the target, new mask output, etc.

**Comment by subdavis** [comment] 2021-11-17 16:26
duplicate of #854

**Closed by subdavis** 2021-11-17 16:26 UTC
