### ISSUE TITLE
[BUG] Investigate transcoding failure

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#914] opened 2021-09-02 12:27 UTC
https://viame.kitware.com/girder#job/613065ea09e68c9d34a43a89
https://viame.kitware.com/girder#job/6137efe669337b2c9a0d2890

**Comment by BryonLewis** [comment] 2021-09-22 14:02
I don't know if I'll get to the root cause of the issue but I'm recording some information here to hopefully help:
So far I can tell that both of these videos were using a similar camera based on the metadata included.
They both seem to be goPros and the recordings are using the AV1 codec but have different frame rates, Spider is 27.97 and the EMF one is 59.94.

So there is some similarity between the two in regards to AV1, but the failures are different.

**Comment by BryonLewis** [comment] 2021-09-24 14:42
Transcodes did eventually succeed after running again.  I've gone through and transcoded each file again as well and it succeeded.  The issues weren't reproducible, gathered enough info for future comparison if it happens again so I'm closing the issue.

**Closed by BryonLewis** 2021-09-24 14:42 UTC
Labels: Type: bug, skipped-planning, Affects: Web
